export const productPrefix = '/admin/products'
export const categoryPrefix = '/admin/categories'
export const brandPrefix = '/admin/brands'
export const userPrefix = '/admin/users'
export const attributeGroupPrefix = '/admin/attribute-groups'
export const bannerPrefix = '/admin/banners'
